### ISSUE TITLE
agent-collector exited with code 5

### ISSUE THREAD

**Issue by superbag2010** [monasca/monasca-docker#128] opened 2017-07-22 12:07 UTC
After 'docker-compose up', about for 20 hours, all conainter had worked well. However, suddenly agent-collector exited as following.
![image](https://user-images.githubusercontent.com/17903225/28490919-9d607708-6f20-11e7-9f0e-e22f5c586d43.png)

That time was about 'Sat 2017-07-22 06:50:49 UTC'. I traced agent-collector container log as following, but any error-similar message doesn't exist.
![image](https://user-images.githubusercontent.com/17903225/28490957-72a9222a-6f21-11e7-8fbc-c1f61e376696.png)

Could you give me any idea? In advance, thank you.

**Comment by timothyb89** [comment] 2017-07-26 21:42
Hmm, it looks like you might've a core dumping issue we've been seeing from the agent, so far we haven't been able to find the cause. As a workaround you can set `restart: on-failure` for the agent-collector container in docker-compose.yml to have docker restart it automatically.

**Comment by craigbr** [comment] 2017-07-26 22:29
It looks like the collector exited after 24 hours. The other pods had been up 29 hours and the collector had exited 5 hours ago. This is just the default behavior of the collector. There were issues with the collector python process memory growing over time so it was changed to exit every 24 hours. So, we should probably add the `restart: on-failure` to docker-compose.yaml as the default.

Unfortunately, this is not the core dump issue.

**Comment by timothyb89** [comment] 2017-08-14 22:47
I think this will be fixed by #160

**Comment by kornicameister** [comment] 2017-08-25 19:54
@timothyb89 can we close it now ?

**Comment by digitalfishpond** [comment] 2017-09-13 11:19
Currently, after 24 hours, the status of `monascadocker_agent-collector_1` is no longer reported with docker ps:

After 23 hours:
![agent-collector_23hrs](https://user-images.githubusercontent.com/13361549/30374672-fe6ea40a-9885-11e7-8ece-cec103094bde.png)

After 25 hours:
![agent-collector_25hrs](https://user-images.githubusercontent.com/13361549/30374678-0360b296-9886-11e7-9f41-eead79ed0b37.png)

**Comment by timothyb89** [comment] 2017-09-13 17:11
@kornicameister @digitalfishpond I think my previous comment was incorrect, the 24 hour restart is the issue @craigbr mentioned in https://github.com/monasca/monasca-docker/issues/128#issuecomment-318201641. The fix here is to add `restart: unless-stopped` to the collector in `docker-compose.yml` - which really we ought to specify by default.

(note that the previous suggestion of `restart: unless-stopped` probably will not give us the behavior we want... I think the collector returns 0 when it exits like this)

**Comment by craigbr** [comment] 2017-09-13 19:21
As I stated above, the collector is designed to exit every 24 hours. I created https://github.com/monasca/monasca-docker/pull/212 to set the restart policy as Tim suggested above.

**Comment by timothyb89** [comment] 2017-09-15 22:36
I think this should be fixed with #212

**Closed by timothyb89** 2017-09-15 22:36 UTC
Labels: bug

**Comment by digitalfishpond** [comment] 2017-09-18 05:39
Confirming that #212 fixed the problem.
![selection_001](https://user-images.githubusercontent.com/13361549/30530127-6f12dfac-9c44-11e7-987b-8bd11d59e94b.png)
